openapi: 3.0.1
info:
  title: free-movie
  version: 1.0.0
servers:
- url: /
tags:
- name: api
- name: login
- name: rule
paths:
  /api/rule:
    delete:
      deprecated: false
      description: 删除规则
      operationId: removeRule
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                properties: {}
                type: object
                x-apifox-orders: []
                x-apifox-ignore-properties: []
          description: Success
        "401":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error
      summary: /api/rule
      tags:
      - rule
      x-apifox-folder: rule
      x-apifox-status: released
      x-eov-operation-handler: controllers/RuleController
    get:
      deprecated: false
      description: 获取规则列表
      operationId: rule
      parameters:
      - description: 当前的页码
        explode: true
        in: query
        name: current
        required: false
        schema:
          type: string
        style: form
      - description: 页面的容量
        explode: true
        in: query
        name: pageSize
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/RuleList'
          description: Success
        "401":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error
      summary: /api/rule
      tags:
      - rule
      x-apifox-folder: rule
      x-apifox-status: released
      x-eov-operation-handler: controllers/RuleController
    post:
      deprecated: false
      description: 新建规则
      operationId: addRule
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/RuleListItem'
          description: Success
        "401":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error
      summary: /api/rule
      tags:
      - rule
      x-apifox-folder: rule
      x-apifox-status: released
      x-eov-operation-handler: controllers/RuleController
    put:
      deprecated: false
      description: 新建规则
      operationId: updateRule
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/RuleListItem'
          description: Success
        "401":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error
      summary: /api/rule
      tags:
      - rule
      x-apifox-folder: rule
      x-apifox-status: released
      x-eov-operation-handler: controllers/RuleController
  /api/login/account:
    post:
      deprecated: false
      description: 登录接口
      operationId: login
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginParams'
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/LoginResult'
          description: Success
        "401":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error
      summary: /api/login/account
      tags:
      - login
      x-apifox-folder: login
      x-apifox-status: released
      x-eov-operation-handler: controllers/LoginController
  /api/notices:
    get:
      deprecated: false
      operationId: getNotices
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/NoticeIconList'
          description: Success
      summary: /api/notices
      tags:
      - api
      x-apifox-folder: api
      x-apifox-status: released
      x-eov-operation-handler: controllers/ApiController
  /api/login/captcha:
    post:
      deprecated: false
      description: 发送验证码
      operationId: getFakeCaptcha
      parameters:
      - description: 手机号
        explode: true
        in: query
        name: phone
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/FakeCaptcha'
          description: Success
      summary: /api/login/captcha
      tags:
      - login
      x-apifox-folder: login
      x-apifox-status: released
      x-eov-operation-handler: controllers/LoginController
  /api/login/outLogin:
    post:
      deprecated: false
      description: 登录接口
      operationId: outLogin
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                properties: {}
                type: object
                x-apifox-orders: []
                x-apifox-ignore-properties: []
          description: Success
        "401":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error
      summary: /api/login/outLogin
      tags:
      - login
      x-apifox-folder: login
      x-apifox-status: released
      x-eov-operation-handler: controllers/LoginController
  /api/currentUser:
    get:
      deprecated: false
      description: 获取当前的用户
      operationId: currentUser
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/CurrentUser'
          description: Success
        "401":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error
      summary: /api/currentUser
      tags:
      - api
      x-apifox-folder: api
      x-apifox-status: released
      x-eov-operation-handler: controllers/ApiController
components:
  schemas:
    NoticeIconList:
      properties:
        data:
          items:
            $ref: '#/components/schemas/NoticeIconItem'
          type: array
        total:
          description: 列表的内容总数
          format: int32
          type: integer
        success:
          type: boolean
      type: object
      x-apifox-orders:
      - data
      - total
      - success
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    NoticeIconItemType:
      description: 已读未读列表的枚举
      enum:
      - notification
      - message
      - event
      properties: {}
      title: NoticeIconItemType
      type: string
      x-apifox-folder: Schemas
    ErrorResponse:
      properties:
        errorCode:
          description: 业务约定的错误码
          type: string
        errorMessage:
          description: 业务上的错误信息
          type: string
        success:
          description: 业务上的请求是否成功
          type: boolean
      required:
      - errorCode
      type: object
      x-apifox-orders:
      - errorCode
      - errorMessage
      - success
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    LoginResult:
      properties:
        status:
          type: string
        type:
          type: string
        currentAuthority:
          type: string
      type: object
      x-apifox-orders:
      - status
      - type
      - currentAuthority
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    LoginParams:
      properties:
        username:
          type: string
        password:
          type: string
        autoLogin:
          type: boolean
        type:
          type: string
      type: object
      x-apifox-orders:
      - username
      - password
      - autoLogin
      - type
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    RuleList:
      properties:
        data:
          items:
            $ref: '#/components/schemas/RuleListItem'
          type: array
        total:
          description: 列表的内容总数
          format: int32
          type: integer
        success:
          type: boolean
      type: object
      x-apifox-orders:
      - data
      - total
      - success
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    PageParams:
      properties:
        current:
          type: number
        pageSize:
          type: number
      type: object
      x-apifox-orders:
      - current
      - pageSize
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    RuleListItem:
      properties:
        key:
          format: int32
          type: integer
        disabled:
          type: boolean
        href:
          type: string
        avatar:
          type: string
        name:
          type: string
        owner:
          type: string
        desc:
          type: string
        callNo:
          format: int32
          type: integer
        status:
          format: int32
          type: integer
        updatedAt:
          format: datetime
          type: string
        createdAt:
          format: datetime
          type: string
        progress:
          format: int32
          type: integer
      type: object
      x-apifox-orders:
      - key
      - disabled
      - href
      - avatar
      - name
      - owner
      - desc
      - callNo
      - status
      - updatedAt
      - createdAt
      - progress
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    FakeCaptcha:
      properties:
        code:
          format: int32
          type: integer
        status:
          type: string
      type: object
      x-apifox-orders:
      - code
      - status
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    NoticeIconItem:
      properties:
        id:
          type: string
        extra:
          format: any
          type: string
        key:
          type: string
        read:
          type: boolean
        avatar:
          type: string
        title:
          type: string
        status:
          type: string
        datetime:
          format: date
          type: string
        description:
          type: string
        type:
          $ref: '#/components/schemas/NoticeIconItemType'
      type: object
      x-apifox-orders:
      - id
      - extra
      - key
      - read
      - avatar
      - title
      - status
      - datetime
      - description
      - type
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    CurrentUser:
      properties:
        name:
          type: string
        avatar:
          type: string
        userid:
          type: string
        email:
          type: string
        signature:
          type: string
        title:
          type: string
        group:
          type: string
        tags:
          items:
            $ref: '#/components/schemas/CurrentUser_tags'
          type: array
        notifyCount:
          format: int32
          type: integer
        unreadCount:
          format: int32
          type: integer
        country:
          type: string
        access:
          type: string
        geographic:
          $ref: '#/components/schemas/CurrentUser_geographic'
        address:
          type: string
        phone:
          type: string
      type: object
      x-apifox-orders:
      - name
      - avatar
      - userid
      - email
      - signature
      - title
      - group
      - tags
      - notifyCount
      - unreadCount
      - country
      - access
      - geographic
      - address
      - phone
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    CurrentUser_tags:
      properties:
        key:
          type: string
        label:
          type: string
    CurrentUser_geographic_province:
      properties:
        label:
          type: string
        key:
          type: string
    CurrentUser_geographic:
      properties:
        province:
          $ref: '#/components/schemas/CurrentUser_geographic_province'
        city:
          $ref: '#/components/schemas/CurrentUser_geographic_province'
