env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules: {
  'react/jsx-filename-extension': [ 1, { extensions: [ '.js', '.jsx', '.tsx' ] } ],
  "import/no-unresolved": "off",
  "import/extensions": "off",
  'import/no-extraneous-dependencies': "off",
  indent: [ "error", 2 ],
}
